Fix syntax error
hexagon-geo-surv/mwifiex pull request #6
Opened 2022-11-13 22:54 UTC by depau

This prevents building the module. By the way, this also builds correctly on 5.19, thanks for sharing these changes.

2022-12-12 21:00 UTC, zandrey requested changes
Thanks for sharing this fix! 👍🏻 

There is a styling issue with your commit, specifically:

Can you please adjust the commit message according the [_Kernel Patch Submission Process_](https://www.kernel.org/doc/html/latest/process/submitting-patches.html)?

We are following same commit style in this repo as in Kernel, so commit messages has to be aligned, especially in `Signed-off-by:` part.

-- andrey

2022-12-12 21:27 UTC, depau commented
No problem :) I signed it off and added an appropriate driver prefix, let me know if there's anything else you'd like me to address

2022-12-13 07:36 UTC, zandrey approved these changes
LGTM

2022-12-13 10:03 UTC, htho-lgs reviewed
LGTM

2022-12-13 21:37 UTC, merged